#!/usr/bin/env python

import os
import sys


def main():
    if len(sys.argv) < 3:
        print "{} <env.cfg> <command>".format(sys.argv[0])
        sys.exit(1)

    with open(sys.argv[1]) as fp:
        for line in fp:
            if not line.strip():
                continue

            key, value = line.split("=", 1)
            os.putenv(key.strip(), value.strip())

    os.execvp(sys.argv[2], sys.argv[2:])


if __name__ == "__main__":
    main()
